### ISSUE TITLE
Data Downloading Issue

### ISSUE THREAD

**Issue by BlueCat-de** [hustvl/DiffusionDrive#11]
Hi there!
Have you tried to use `super_download.sh` for data downloading? Error occurs while I'm tring to use it.

**Comment by Jzzzi** [comment]
@BlueCat-de 


> Hi there! Have you tried to use `super_download.sh` for data downloading? Error occurs while I'm tring to use it.

Actually I write it and test it on my server machine. Could you please show the error you met?
