### ISSUE TITLE
question about DDIM step

### ISSUE THREAD

**Issue by YiJiangYue** [hustvl/DiffusionDrive#12]
非常感谢您的工作！
我想请问一下这里DDIM step输入的model_output对应的是trajectory？diffusion_scheduler的prediction_type是不是应该为‘sample’？
![image](https://github.com/user-attachments/assets/5fc13c22-589a-4f66-a910-aaeaad932382)

**Comment by LegendBC** [comment]
Thank you for pointing this out! It seems that I made an error while migrating and cleaning up the code. You are correct, the `prediction_type="sample"` in the DDIM scheduler. I have corrected this in the latest code.
