### ISSUE TITLE
Evaluating the provided checkpoint

### ISSUE THREAD

**Issue by varunjammula** [hustvl/DiffusionDrive#23]
When I try to evaluate using the provided model from huggingface, I get the following error: 

` File "/scratch/vjammula/ddrive/navsim/agents/diffusiondrive/transfuser_agent.py", line 54, in __init__
    self.init_from_pretrained()
  File "/scratch/vjammula/ddrive/navsim/agents/diffusiondrive/transfuser_agent.py", line 62, in init_from_pretrained
    checkpoint = torch.load(self._checkpoint_path, map_location=torch.device('cpu'))
  File "/home/vjammula/.conda/envs/ddrive/lib/python3.9/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/vjammula/.conda/envs/ddrive/lib/python3.9/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

The above exception was the direct cause of the following exception:`

**Comment by varunjammula** [comment]
I will check it again and report back, thanks!

**Comment by varunjammula** [comment]
Inference code works on my setup as well with the models I trained. The model uploaded to hface has no extension (ckpt/pth). I cloned the hface repo using git and it still does not work.

**Comment by LegendBC** [comment]
you can try renaming it with `.ckpt` extension

**Comment by varunjammula** [comment]
Tried that but still doesn’t work!

**Comment by BlueCat-de** [comment]
I directly used the provided name(no extension) and it worked.

**Comment by varunjammula** [comment]
I tried that too 😭along with adding ckpt or pth extensions to no success. @BlueCat-de is your code up to date with master?

**Comment by BlueCat-de** [comment]
> I tried that too along with adding ckpt or pth extensions to no success. @BlueCat-de is your code up to date with main?

I changed my code following the instructions from https://github.com/hustvl/DiffusionDrive/issues/10#issuecomment-2550665598.

**Comment by LegendBC** [comment]
@varunjammula I tried inference with the latest code, it works on both w/ and w/o ckpt extension. Can you just try directly loading the checkpoint in your Python shell instead of running the command?

**Comment by LegendBC** [comment]
@varunjammula Can you try this test?
![image](https://github.com/user-attachments/assets/e9cdc8d5-cc92-4eb5-abf7-e006f1c3ef06)

**Comment by varunjammula** [comment]
Here is my log

![Screenshot from 2024-12-30 22-14-23](https://github.com/user-attachments/assets/8f69b0fe-8760-410e-928d-e7c6694e30eb)

**Comment by LegendBC** [comment]
@varunjammula can you check the file size? I doubt that the downloaded file may be incomplete. You can download through the HTML page and then upload it to your local machine.
![image](https://github.com/user-attachments/assets/32b38e53-26f0-4089-bcd8-b3c0a2fb6130)

**Comment by LegendBC** [comment]
You can check this thread for similar issue, https://github.com/svip-lab/PlanarReconstruction/issues/28, which is raised by an incomplete download. You can download it manually and upload it.

**Comment by varunjammula** [comment]
That worked.

**Comment by LegendBC** [comment]
> Inference code works on my setup as well with the models I trained. The model uploaded to hface has no extension (ckpt/pth). I cloned the hface repo using git and it still does not work.

I recommend using `huggingface-cli download` instead of `git`, which can not resume and may not inform.
