### ISSUE TITLE
Why is your loss not the traditional diffusion loss?

### ISSUE THREAD

**Issue by 2460707925** [hustvl/DiffusionDrive#3]
因为原始的diffusion 的过程是预测噪声然后不断的减去噪声进行生成，但是你们的网络是直接输出去噪的轨迹，感觉是一个corse to fine的过程（广义的diffusion?），论文的loss 也没有diffusion 的loss，此外直接使用anchor去给轨迹会不会导致后续网络只需要进行分类选择更合适的anchor 并进行微调，对于复杂场景有没有进行实验与验证呢？

**Comment by LegendBC** [comment]
Thank you for your comment! We'd like to clarify that instead of directly predicting the final trajectory, as you mentioned, our approach diffuses the anchor points with a truncated noise schedule to generate noisy trajectories. We then predict the offset of these noisy trajectories, which corresponds to the predicted noise in traditional diffusion loss.

Regarding the NAVSIM dataset, it serves as a large-scale and complex benchmark, encompassing challenging scenarios for end-to-end autonomous driving. Our model's significant performance gains on NAVSIM underscore its effectiveness. Additionally, we have provided real-world demonstrations to showcase the model's capability to handle complex, real-world driving scenarios.

**Comment by 2460707925** [comment]
不好意思，我在论文中并没找到预测offset的相关描述，您能指出在哪里嘛。

**Comment by LegendBC** [comment]
here in Page 6
![image](https://github.com/user-attachments/assets/ee4faec9-ec7e-4108-9c11-47fa08f20a24)

**Comment by JLUtangchuan** [comment]
I have the same question, In Form 6, the regression loss supervises the output trajectory and the ground truth trajectory.
![image](https://github.com/user-attachments/assets/c139a673-8181-4646-89f5-61dae870b3e4)

**Comment by LegendBC** [comment]
> I have the same question, In Form 6, the regression loss supervises the output trajectory and the ground truth trajectory. ![image](https://private-user-images.githubusercontent.com/26868168/393064937-c139a673-8181-4646-89f5-61dae870b3e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzU4MDAsIm5iZiI6MTczMzczNTUwMCwicGF0aCI6Ii8yNjg2ODE2OC8zOTMwNjQ5MzctYzEzOWE2NzMtODE4MS00NjQ2LTg5ZjUtNjFkYWU4NzBiM2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA5MTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZDc0YjQ2YmIxMjIxMDc4MWI3ZGQwZGE5NGJhZjBiZDQ2ZDZmOTJiMzg0YWM3MTA2MjBlYTI4ZmJhZDEyNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TnPrTKjGx-aeM1TgBV9jS9gIsDFpqe8d5IKy57AXQfM)

@JLUtangchuan output_traj=noisy_traj+predicted offset, so the loss is calculated between predicted offset and added noise

**Comment by wsakobe** [comment]
I’m also curious about why L1 Loss can be used here. Based on my understanding, the denoising process here is essentially predicting the ground truth trajectory  **gt_traj = anchor_traj + offset** under the given condition, using **noise_traj = anchor_traj + noise** as input. So, does the reconstruction loss in Form 6 refer to  \text{noise} - \text{offset} ? If this is a diffusion process, shouldn’t L2 Loss be used instead?

**Comment by Agito555** [comment]
> I’m also curious about why L1 Loss can be used here. Based on my understanding, the denoising process here is essentially predicting the ground truth trajectory **gt_traj = anchor_traj + offset** under the given condition, using **noise_traj = anchor_traj + noise** as input. So, does the reconstruction loss in Form 6 refer to **noise - offset**? If this is a diffusion process, shouldn’t L2 Loss be used instead?

Same question here. I'm also unsure how the diffusion model contributes in this context.
Typically, diffusion models learn data distributions by progressively adding and removing noise.
However, in this case, it seems that the model simply samples noise from a centered Gaussian distribution to learn the ground-truth trajectory. I don't quite know how to interpret this.
