### ISSUE TITLE
Issue about For.6 ,what does noise_traj and offset mean?

### ISSUE THREAD

**Issue by Zhihua-Hua** [hustvl/DiffusionDrive#4]
Hi,awesome work! But I have some questions about For.6
![image](https://github.com/user-attachments/assets/cfbc138b-f030-46eb-ae05-9a1d2620ff1e)
In this For.  reference to previous issue reply,does that mean
![image](https://github.com/user-attachments/assets/7ec6263d-3805-4fdf-a7e4-7764c33c529c) = noise_traj + offset? 
Does offset mean diffusion noise?
If so, noise_traj means what and how to get the noise_traj? Thank you!

**Comment by LegendBC** [comment]
Hi @Zhihua-Hua, thanks for your interest. Noise_traj means the clustered anchors.

**Comment by Zhihua-Hua** [comment]
Thank you for your reply! Can I understand the method in this way, you use the clustered anchors(Noise_traj) adding noise as the noise_trajs and input this into the diffusion, then the diffusion outputs the noise(offset) as the supervised result? Look forward to your reply!

**Comment by Zhihua-Hua** [comment]
If so, does that mean the diffusion model learning the clustered anchor? Could you please interpret the thought in detail, I have struggled with it for a long time, thank you very much!

**Comment by LegendBC** [comment]
> Thank you for your reply! Can I understand the method in this way, you use the clustered anchors(Noise_traj) adding noise as the noise_trajs and input this into the diffusion, then the diffusion outputs the noise(offset) as the supervised result? Look forward to your reply!

yes, ur understanding is right.

**Comment by LegendBC** [comment]
> If so, does that mean the diffusion model learning the clustered anchor? Could you please interpret the thought in detail, I have struggled with it for a long time, thank you very much!

No, we generate clusters anchors offline on train split before training the model. During training, we directly use the clustered anchor.
