### ISSUE TITLE
Questions about the input and output of the Diffusion Decoder Layer

### ISSUE THREAD

**Issue by Hamusukesama** [hustvl/DiffusionDrive#5]
Hi. Thank you for your brilliant work and look forward to the code!
I have a few questions and hope to get answers:
1. What is the output of the diffusion layer? Suppose the input is noisy_traj (corresponding to anchor + noise of t steps, 0<t<50)
    a.  noise of one step (which is the noise added to anchor and is not related to gt)
    b. offset from noisy_traj to gt
    c. something else
2. How many diffusion timesteps are involved in training and inference, respectively?
    a. one for training (such as DDPM, t -> t-1 ), and two steps for inference (DDIM, 50 -> 25 -> 0)
    b. something else
Thank you again!

**Comment by LegendBC** [comment]
> Hi. Thank you for your brilliant work and look forward to the code!
> I have a few questions and hope to get answers:
> 1. What is the output of the diffusion layer? Suppose the input is noisy_traj (corresponding to anchor + noise of t steps, 0<t<50)
>     a.  noise of one step (which is the noise added to anchor and is not related to gt)
>     b. offset from noisy_traj to gt
>     c. something else
> 2. How many diffusion timesteps are involved in training and inference, respectively?
>     a. one for training (such as DDPM, t -> t-1 ), and two steps for inference (DDIM, 50 -> 25 -> 0)
>     b. something else
> Thank you again!

Thanks for your interest! For question 1, the answer is b. For question 2, the answer is a.

**Comment by LegendBC** [comment]
We have released an initial version of the code and weight, you can check the implementation for further details!
