### ISSUE TITLE
Could not find 'agent/diffusiondrive_agent

### ISSUE THREAD

**Issue by hey-cjj** [hustvl/DiffusionDrive#6]
I executed the command for caching the dataset for training as follows:

`python navsim/planning/script/run_dataset_caching.py agent=diffusiondrive_agent experiment_name=training_diffusiondrive_agent train_test_split=navtrain12.13.49.33_veh-28_02007_02129`

I got these:

```
In 'default_training': Could not find 'agent/diffusiondrive_agent'

Available options in 'agent':
        constant_velocity_agent
        ego_status_mlp_agent
        human_agent
        transfuser_agent
Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file:///home/levi.cao/DiffusionDrive/navsim/planning/script/config/training
        provider=hydra.searchpath in main, path=pkg://navsim.planning.script.config.common
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

What's more, if agent=transfuser_agent, it works. Could you please tell me what's wrong?

**Comment by LegendBC** [comment]
You can directly use the transfuser_agent to cache the dataset, it is the same as Diffusiondrive.

**Comment by hey-cjj** [comment]
I fixed it by adding path of Diffusiondrrive to ~/.bashrc

**Comment by varunjammula** [comment]
@hey-cjj Did you add it to PYTHONPATH? I did the same and still see the same error!

**Comment by hey-cjj** [comment]
> @hey-cjj Did you add it to PYTHONPATH? I did the same and still see the same error!

`export PYTHONPATH=$PYTHONPATH:/home/DiffusionDrive`
