### ISSUE TITLE
Train on a single 4090?

### ISSUE THREAD

**Issue by Hongbo123467** [hustvl/DiffusionDrive#8]
Could the model be trained on a single 4090?
Do the corresponding training parameter settings (eg. learning rate) need to be adjusted?

**Comment by LegendBC** [comment]
We train on 8 4090 GPUs.

> Do the corresponding training parameter settings (eg. learning rate) need to be adjusted?

Yes, the learning rate should be adjusted if you use only 1 GPU.

**Comment by gzspkgypt** [comment]
I'm straight-up autistic, I only have one 3090.
